<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="05e1b537-9c33-405f-abaa-497df3b44d49" name="JWang@DEV-DSKFPV02 2015-11-16 14:47:17" runUser="IMO\JWang" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Default Test Settings" id="9f8b9c3b-9038-4c14-8373-3e0d41939844">
    <Deployment userDeploymentRoot="C:\Octopus\Applications\CRM API Integration Tests Dev\CRM.API.IntegrationTests\1.0.0.113_2" useDefaultDeploymentRoot="false" runDeploymentRoot="JWang_DEV-DSKFPV02 2015-11-16 14_47_17" />
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
    <Properties />
  </TestSettings>
  <Times creation="2015-11-16T14:47:17.9345585-06:00" queuing="2015-11-16T14:47:18.6826333-06:00" start="2015-11-16T14:47:18.8866537-06:00" finish="2015-11-16T14:47:24.3261976-06:00" />
  <ResultSummary outcome="Failed">
    <Counters total="2" executed="2" error="0" failed="2" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="DEV-DSKFPV02" outcome="Warning" timestamp="2015-11-16T14:47:18.4126063-06:00">
        <Text>Warning: Test Run deployment issue: The assembly or module 'Microsoft.IdentityModel' directly or indirectly referenced by the test container 'c:\octopus\applications\crm api integration tests dev\crm.api.integrationtests\1.0.0.113_2\crm.api.integrationtests.dll' was not found.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="integrationTest_TestAutomated" storage="c:\octopus\applications\crm api integration tests dev\crm.api.integrationtests\1.0.0.113_2\crm.api.integrationtests.dll" id="48909555-bbbe-d354-e244-745c6bd7cbae">
      <Execution id="e00cdd44-ae85-4f21-a779-5650affc3cab" />
      <Properties>
        <Property>
          <Key>__Internal_AsyncTypeName__</Key>
          <Value>CRM.API.IntegrationTests.MIgrationControllerTest+&lt;integrationTest_TestAutomated&gt;d__5</Value>
        </Property>
      </Properties>
      <TestMethod codeBase="C:/Octopus/Applications/CRM API Integration Tests Dev/CRM.API.IntegrationTests/1.0.0.113_2/CRM.API.IntegrationTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="CRM.API.IntegrationTests.MIgrationControllerTest, CRM.API.IntegrationTests, Version=1.0.0.113, Culture=neutral, PublicKeyToken=null" name="integrationTest_TestAutomated" />
    </UnitTest>
    <UnitTest name="integrationTest_SetupCrm" storage="c:\octopus\applications\crm api integration tests dev\crm.api.integrationtests\1.0.0.113_2\crm.api.integrationtests.dll" id="b4b8a08e-4f3c-14cc-c824-2631d3cb6fff">
      <Execution id="582f29d4-7dc3-416c-8ace-de66114be194" />
      <Properties>
        <Property>
          <Key>__Internal_AsyncTypeName__</Key>
          <Value>CRM.API.IntegrationTests.MIgrationControllerTest+&lt;integrationTest_SetupCrm&gt;d__0</Value>
        </Property>
      </Properties>
      <TestMethod codeBase="C:/Octopus/Applications/CRM API Integration Tests Dev/CRM.API.IntegrationTests/1.0.0.113_2/CRM.API.IntegrationTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="CRM.API.IntegrationTests.MIgrationControllerTest, CRM.API.IntegrationTests, Version=1.0.0.113, Culture=neutral, PublicKeyToken=null" name="integrationTest_SetupCrm" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="b4b8a08e-4f3c-14cc-c824-2631d3cb6fff" executionId="582f29d4-7dc3-416c-8ace-de66114be194" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="48909555-bbbe-d354-e244-745c6bd7cbae" executionId="e00cdd44-ae85-4f21-a779-5650affc3cab" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="582f29d4-7dc3-416c-8ace-de66114be194" testId="b4b8a08e-4f3c-14cc-c824-2631d3cb6fff" testName="integrationTest_SetupCrm" computerName="DEV-DSKFPV02" duration="00:00:02.6695699" startTime="2015-11-16T14:47:18.9636614-06:00" endTime="2015-11-16T14:47:22.1539804-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="582f29d4-7dc3-416c-8ace-de66114be194">
      <Output>
        <ErrorInfo>
          <Message>Test method CRM.API.IntegrationTests.MIgrationControllerTest.integrationTest_SetupCrm threw exception: 
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:53328</Message>
          <StackTrace>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)
 --- End of inner exception stack trace ---
    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext&amp; context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
 --- End of inner exception stack trace ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CRM.API.IntegrationTests.MIgrationControllerTest.&lt;integrationTest_SetupCrm&gt;d__0.MoveNext() in c:\Builds\2\CRMRestAPI\CRM.API\src\src\CRM.API.IntegrationTests\MIgrationControllerTest.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="e00cdd44-ae85-4f21-a779-5650affc3cab" testId="48909555-bbbe-d354-e244-745c6bd7cbae" testName="integrationTest_TestAutomated" computerName="DEV-DSKFPV02" duration="00:00:02.0294129" startTime="2015-11-16T14:47:22.1579808-06:00" endTime="2015-11-16T14:47:24.1931843-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="e00cdd44-ae85-4f21-a779-5650affc3cab">
      <Output>
        <ErrorInfo>
          <Message>Test method CRM.API.IntegrationTests.MIgrationControllerTest.integrationTest_TestAutomated threw exception: 
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:53328</Message>
          <StackTrace>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)
 --- End of inner exception stack trace ---
    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext&amp; context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
 --- End of inner exception stack trace ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CRM.API.IntegrationTests.MIgrationControllerTest.&lt;integrationTest_TestAutomated&gt;d__5.MoveNext() in c:\Builds\2\CRMRestAPI\CRM.API\src\src\CRM.API.IntegrationTests\MIgrationControllerTest.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>