<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="7a5662d8-2b8c-47b3-b79e-c85207cea8ff" name="JWang@DEV-DSKFPV02 2015-11-13 18:21:37" runUser="IMO\JWang" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Default Test Settings" id="0efd8980-564a-49a0-98a8-8af39eee54e4">
    <Deployment userDeploymentRoot="C:\Octopus\Applications\CRM API Integration Tests Dev\CRM.API.IntegrationTests\1.0.0.111_8" useDefaultDeploymentRoot="false" runDeploymentRoot="JWang_DEV-DSKFPV02 2015-11-13 18_21_37" />
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
    <Properties />
  </TestSettings>
  <Times creation="2015-11-13T18:21:37.1210479-06:00" queuing="2015-11-13T18:21:38.1974617-06:00" start="2015-11-13T18:21:38.4002643-06:00" finish="2015-11-13T18:21:41.8011079-06:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="DEV-DSKFPV02" outcome="Warning" timestamp="2015-11-13T18:21:37.7606561-06:00">
        <Text>Warning: Test Run deployment issue: The assembly or module 'Microsoft.IdentityModel' directly or indirectly referenced by the test container 'c:\octopus\applications\crm api integration tests dev\crm.api.integrationtests\1.0.0.111_8\crm.api.integrationtests.dll' was not found.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="integrationTest_SetupCrm" storage="c:\octopus\applications\crm api integration tests dev\crm.api.integrationtests\1.0.0.111_8\crm.api.integrationtests.dll" id="b4b8a08e-4f3c-14cc-c824-2631d3cb6fff">
      <Execution id="6086c170-5b06-4fd2-a83b-4b2c2a44f731" />
      <Properties>
        <Property>
          <Key>__Internal_AsyncTypeName__</Key>
          <Value>CRM.API.IntegrationTests.MIgrationControllerTest+&lt;integrationTest_SetupCrm&gt;d__0</Value>
        </Property>
      </Properties>
      <TestMethod codeBase="C:/Octopus/Applications/CRM API Integration Tests Dev/CRM.API.IntegrationTests/1.0.0.111_8/CRM.API.IntegrationTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="CRM.API.IntegrationTests.MIgrationControllerTest, CRM.API.IntegrationTests, Version=1.0.0.111, Culture=neutral, PublicKeyToken=null" name="integrationTest_SetupCrm" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="b4b8a08e-4f3c-14cc-c824-2631d3cb6fff" executionId="6086c170-5b06-4fd2-a83b-4b2c2a44f731" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="6086c170-5b06-4fd2-a83b-4b2c2a44f731" testId="b4b8a08e-4f3c-14cc-c824-2631d3cb6fff" testName="integrationTest_SetupCrm" computerName="DEV-DSKFPV02" duration="00:00:02.7039645" startTime="2015-11-13T18:21:38.4782653-06:00" endTime="2015-11-13T18:21:41.6919065-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="6086c170-5b06-4fd2-a83b-4b2c2a44f731">
      <Output>
        <ErrorInfo>
          <Message>Test method CRM.API.IntegrationTests.MIgrationControllerTest.integrationTest_SetupCrm threw exception: 
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:53328</Message>
          <StackTrace>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)
 --- End of inner exception stack trace ---
    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext&amp; context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
 --- End of inner exception stack trace ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CRM.API.IntegrationTests.MIgrationControllerTest.&lt;integrationTest_SetupCrm&gt;d__0.MoveNext() in c:\Builds\10\CRMRestAPI\CRM.API\src\src\CRM.API.IntegrationTests\MIgrationControllerTest.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>